name: ZenOS Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies for building...
      run: sudo apt update && sudo apt install -y build-essential nasm xorriso

    - name: Building with make...
      run: make

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: ZenOS.iso
        path: ZenOS.iso
        if-no-files-found: error